/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class qmlbindings {
  public static SWIGTYPE_p_QtQmlBindings_t qtCreateQmlBindings(SWIGTYPE_p_f_p_q_const__char__p_void createObjectFn, SWIGTYPE_p_f_p_void__void destroyObjectFn, SWIGTYPE_p_f_p_void_p_q_const__char__p_QtValue_t readPropertyFn, SWIGTYPE_p_f_p_void_p_q_const__char_p_struct_QtValue_t__void writePropertyFn) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtCreateQmlBindings(SWIGTYPE_p_f_p_q_const__char__p_void.getCPtr(createObjectFn), SWIGTYPE_p_f_p_void__void.getCPtr(destroyObjectFn), SWIGTYPE_p_f_p_void_p_q_const__char__p_QtValue_t.getCPtr(readPropertyFn), SWIGTYPE_p_f_p_void_p_q_const__char_p_struct_QtValue_t__void.getCPtr(writePropertyFn));
    SWIGTYPE_p_QtQmlBindings_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_QtQmlBindings_t(cPtr, false);
    return ret;
  }

  public static void qtDestroyQmlBindings(SWIGTYPE_p_QtQmlBindings_t bindings) {
    qmlbindingsPINVOKE.qtDestroyQmlBindings(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings));
  }

  public static void qtSetBindingsObjectIdentityType(SWIGTYPE_p_QtQmlBindings_t bindings, string typeName) {
    qmlbindingsPINVOKE.qtSetBindingsObjectIdentityType(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), typeName);
  }

  public static void qtSetBindingsUri(SWIGTYPE_p_QtQmlBindings_t bindings, string uri) {
    qmlbindingsPINVOKE.qtSetBindingsUri(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), uri);
  }

  public static void qtSetBindingsVersion(SWIGTYPE_p_QtQmlBindings_t bindings, int majorVersion, int minorVersion) {
    qmlbindingsPINVOKE.qtSetBindingsVersion(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), majorVersion, minorVersion);
  }

  public static SWIGTYPE_p_QtClass_t qtCreateClass(SWIGTYPE_p_QtQmlBindings_t bindings, string className) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtCreateClass(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), className);
    SWIGTYPE_p_QtClass_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_QtClass_t(cPtr, false);
    return ret;
  }

  public static void qtFinalizeClass(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_QtClass_t klass) {
    qmlbindingsPINVOKE.qtFinalizeClass(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_QtClass_t.getCPtr(klass));
  }

  public static void qtCreateProperty(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_QtClass_t klass, string propertyType, string propertyName) {
    qmlbindingsPINVOKE.qtCreateProperty(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_QtClass_t.getCPtr(klass), propertyType, propertyName);
  }

  public static void qtSetClassCompanionType(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_QtClass_t klass, QtClassCompanionType companionType) {
    qmlbindingsPINVOKE.qtSetClassCompanionType(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_QtClass_t.getCPtr(klass), (int)companionType);
  }

  public static SWIGTYPE_p_void qtCreateObject(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_QtClass_t klass) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtCreateObject(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_QtClass_t.getCPtr(klass));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static void qtDestroyObject(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_void arg1) {
    qmlbindingsPINVOKE.qtDestroyObject(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_void.getCPtr(arg1));
  }

  public static void qtWriteProperty(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_void arg1, string propertyName, SWIGTYPE_p_QtValue_t value) {
    qmlbindingsPINVOKE.qtWriteProperty(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_void.getCPtr(arg1), propertyName, SWIGTYPE_p_QtValue_t.getCPtr(value));
  }

  public static SWIGTYPE_p_QtValue_t qtReadProperty(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_void arg1, string propertyName) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtReadProperty(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_void.getCPtr(arg1), propertyName);
    SWIGTYPE_p_QtValue_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_QtValue_t(cPtr, false);
    return ret;
  }

  public static void qtPropertyChanged(SWIGTYPE_p_QtQmlBindings_t bindings, SWIGTYPE_p_void arg1, string propertyName) {
    qmlbindingsPINVOKE.qtPropertyChanged(SWIGTYPE_p_QtQmlBindings_t.getCPtr(bindings), SWIGTYPE_p_void.getCPtr(arg1), propertyName);
  }

  public static int qtMain(int argc, SWIGTYPE_p_p_char argv, string mainQmlFilePath) {
    int ret = qmlbindingsPINVOKE.qtMain(argc, SWIGTYPE_p_p_char.getCPtr(argv), mainQmlFilePath);
    return ret;
  }

  public static int qtMainSimple(string mainQmlFilePath) {
    int ret = qmlbindingsPINVOKE.qtMainSimple(mainQmlFilePath);
    return ret;
  }

  public static int qtValueType(SWIGTYPE_p_QtValue_t value) {
    int ret = qmlbindingsPINVOKE.qtValueType(SWIGTYPE_p_QtValue_t.getCPtr(value));
    return ret;
  }

  public static string qtValueTypeName(int arg0) {
    string ret = qmlbindingsPINVOKE.qtValueTypeName(arg0);
    return ret;
  }

  public static SWIGTYPE_p_QtValue_t qtValueCopy(SWIGTYPE_p_QtValue_t value) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtValueCopy(SWIGTYPE_p_QtValue_t.getCPtr(value));
    SWIGTYPE_p_QtValue_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_QtValue_t(cPtr, false);
    return ret;
  }

  public static void qtValueFree(SWIGTYPE_p_QtValue_t value) {
    qmlbindingsPINVOKE.qtValueFree(SWIGTYPE_p_QtValue_t.getCPtr(value));
  }

  public static int qtValueToInt(SWIGTYPE_p_QtValue_t value) {
    int ret = qmlbindingsPINVOKE.qtValueToInt(SWIGTYPE_p_QtValue_t.getCPtr(value));
    return ret;
  }

  public static SWIGTYPE_p_QtValue_t qtValueFromInt(int value) {
    global::System.IntPtr cPtr = qmlbindingsPINVOKE.qtValueFromInt(value);
    SWIGTYPE_p_QtValue_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_QtValue_t(cPtr, false);
    return ret;
  }

}
