/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: qmlbindings.i */

#define SWIGMODULE qmlbindings
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static void *_swig_goallocate(size_t len) {
  struct {
    size_t len;
    void *ret;
  } a;
  a.len = len;
  crosscall2(_cgo_allocate, &a, (int) sizeof a);
  return a.ret;
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}

#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#include "qmlbindings.h"

#ifdef __cplusplus
extern "C" {
#endif

void
_wrap_qtCreateQmlBindings(void *swig_v)
{
  CreateObjectFn arg1 = (CreateObjectFn) 0 ;
  DestroyObjectFn arg2 = (DestroyObjectFn) 0 ;
  ReadPropertyFn arg3 = (ReadPropertyFn) 0 ;
  WritePropertyFn arg4 = (WritePropertyFn) 0 ;
  QtQmlBindings *result = 0 ;
  
  struct swigargs {
    CreateObjectFn arg1;
    DestroyObjectFn arg2;
    ReadPropertyFn arg3;
    WritePropertyFn arg4;
    long : 0;
    struct QtQmlBindings_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(CreateObjectFn *)&swig_a->arg1; 
  arg2 = *(DestroyObjectFn *)&swig_a->arg2; 
  arg3 = *(ReadPropertyFn *)&swig_a->arg3; 
  arg4 = *(WritePropertyFn *)&swig_a->arg4; 
  
  result = (QtQmlBindings *)qtCreateQmlBindings(arg1,arg2,arg3,arg4);
  *(QtQmlBindings **)&swig_a->result = result; 
}


void
_wrap_qtDestroyQmlBindings(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  
  qtDestroyQmlBindings(arg1);
  
}


void
_wrap_qtSetBindingsObjectIdentityType(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  char *arg2 = (char *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    _gostring_ arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  qtSetBindingsObjectIdentityType(arg1,(char const *)arg2);
  
}


void
_wrap_qtSetBindingsUri(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  char *arg2 = (char *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    _gostring_ arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  qtSetBindingsUri(arg1,(char const *)arg2);
  
}


void
_wrap_qtSetBindingsVersion(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  int arg2 ;
  int arg3 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    intgo arg2;
    intgo arg3;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = (int)swig_a->arg2; 
  arg3 = (int)swig_a->arg3; 
  
  qtSetBindingsVersion(arg1,arg2,arg3);
  
}


void
_wrap_qtCreateClass(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  char *arg2 = (char *) 0 ;
  QtClass *result = 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    _gostring_ arg2;
    long : 0;
    struct QtClass_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  result = (QtClass *)qtCreateClass(arg1,(char const *)arg2);
  *(QtClass **)&swig_a->result = result; 
}


void
_wrap_qtFinalizeClass(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  QtClass *arg2 = (QtClass *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    struct QtClass_t *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(QtClass **)&swig_a->arg2; 
  
  qtFinalizeClass(arg1,arg2);
  
}


void
_wrap_qtCreateProperty(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  QtClass *arg2 = (QtClass *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    struct QtClass_t *arg2;
    _gostring_ arg3;
    _gostring_ arg4;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(QtClass **)&swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = (char *)swig_a->arg4.p; 
  
  qtCreateProperty(arg1,arg2,(char const *)arg3,(char const *)arg4);
  
}


void
_wrap_QtQObjectCompanion(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = QtQObjectCompanion;
  
  swig_a->result = result; 
}


void
_wrap_QuickPaintedItemCompanion(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = QuickPaintedItemCompanion;
  
  swig_a->result = result; 
}


void
_wrap_QtForeginWindowCompanion(void *swig_v)
{
  int result;
  
  struct swigargs {
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  result = QtForeginWindowCompanion;
  
  swig_a->result = result; 
}


void
_wrap_qtSetClassCompanionType(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  QtClass *arg2 = (QtClass *) 0 ;
  QtClassCompanionType arg3 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    struct QtClass_t *arg2;
    intgo arg3;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(QtClass **)&swig_a->arg2; 
  arg3 = (QtClassCompanionType)swig_a->arg3; 
  
  qtSetClassCompanionType(arg1,arg2,arg3);
  
}


void
_wrap_qtCreateObject(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  QtClass *arg2 = (QtClass *) 0 ;
  void *result = 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    struct QtClass_t *arg2;
    long : 0;
    void *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(QtClass **)&swig_a->arg2; 
  
  result = (void *)qtCreateObject(arg1,arg2);
  *(void **)&swig_a->result = result; 
}


void
_wrap_qtDestroyObject(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  void *arg2 = (void *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    void *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(void **)&swig_a->arg2; 
  
  qtDestroyObject(arg1,arg2);
  
}


void
_wrap_qtWriteProperty(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  void *arg2 = (void *) 0 ;
  char *arg3 = (char *) 0 ;
  QtValue *arg4 = (QtValue *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    void *arg2;
    _gostring_ arg3;
    struct QtValue_t *arg4;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(void **)&swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = *(QtValue **)&swig_a->arg4; 
  
  qtWriteProperty(arg1,arg2,(char const *)arg3,arg4);
  
}


void
_wrap_qtReadProperty(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  void *arg2 = (void *) 0 ;
  char *arg3 = (char *) 0 ;
  QtValue *result = 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    void *arg2;
    _gostring_ arg3;
    long : 0;
    struct QtValue_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(void **)&swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  
  result = (QtValue *)qtReadProperty(arg1,arg2,(char const *)arg3);
  *(QtValue **)&swig_a->result = result; 
}


void
_wrap_qtPropertyChanged(void *swig_v)
{
  QtQmlBindings *arg1 = (QtQmlBindings *) 0 ;
  void *arg2 = (void *) 0 ;
  char *arg3 = (char *) 0 ;
  
  struct swigargs {
    struct QtQmlBindings_t *arg1;
    void *arg2;
    _gostring_ arg3;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtQmlBindings **)&swig_a->arg1; 
  arg2 = *(void **)&swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  
  qtPropertyChanged(arg1,arg2,(char const *)arg3);
  
}


void
_wrap_qtMain(void *swig_v)
{
  int arg1 ;
  char **arg2 = (char **) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  struct swigargs {
    intgo arg1;
    char **arg2;
    _gostring_ arg3;
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (int)swig_a->arg1; 
  arg2 = *(char ***)&swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  
  result = (int)qtMain(arg1,arg2,(char const *)arg3);
  swig_a->result = result; 
}


void
_wrap_qtMainSimple(void *swig_v)
{
  char *arg1 = (char *) 0 ;
  int result;
  
  struct swigargs {
    _gostring_ arg1;
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (char *)swig_a->arg1.p; 
  
  result = (int)qtMainSimple((char const *)arg1);
  swig_a->result = result; 
}


void
_wrap_qtValueType(void *swig_v)
{
  QtValue *arg1 = (QtValue *) 0 ;
  int result;
  
  struct swigargs {
    struct QtValue_t *arg1;
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtValue **)&swig_a->arg1; 
  
  result = (int)qtValueType(arg1);
  swig_a->result = result; 
}


void
_wrap_qtValueTypeName(void *swig_v)
{
  int arg1 ;
  char *result = 0 ;
  
  struct swigargs {
    intgo arg1;
    long : 0;
    _gostring_ result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (int)swig_a->arg1; 
  
  result = (char *)qtValueTypeName(arg1);
  swig_a->result = _swig_makegostring((char*)result, result ? strlen((char*)result) : 0); 
}


void
_wrap_qtValueCopy(void *swig_v)
{
  QtValue *arg1 = (QtValue *) 0 ;
  QtValue *result = 0 ;
  
  struct swigargs {
    struct QtValue_t *arg1;
    long : 0;
    struct QtValue_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtValue **)&swig_a->arg1; 
  
  result = (QtValue *)qtValueCopy(arg1);
  *(QtValue **)&swig_a->result = result; 
}


void
_wrap_qtValueFree(void *swig_v)
{
  QtValue *arg1 = (QtValue *) 0 ;
  
  struct swigargs {
    struct QtValue_t *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtValue **)&swig_a->arg1; 
  
  qtValueFree(arg1);
  
}


void
_wrap_qtValueToInt(void *swig_v)
{
  QtValue *arg1 = (QtValue *) 0 ;
  int result;
  
  struct swigargs {
    struct QtValue_t *arg1;
    long : 0;
    intgo result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(QtValue **)&swig_a->arg1; 
  
  result = (int)qtValueToInt(arg1);
  swig_a->result = result; 
}


void
_wrap_qtValueFromInt(void *swig_v)
{
  int arg1 ;
  QtValue *result = 0 ;
  
  struct swigargs {
    intgo arg1;
    long : 0;
    struct QtValue_t *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (int)swig_a->arg1; 
  
  result = (QtValue *)qtValueFromInt(arg1);
  *(QtValue **)&swig_a->result = result; 
}


#ifdef __cplusplus
}
#endif

