/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class qmlbindingsJNI {
  public final static native long qtCreateQmlBindings(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void qtDestroyQmlBindings(long jarg1);
  public final static native void qtSetBindingsObjectIdentityType(long jarg1, String jarg2);
  public final static native void qtSetBindingsUri(long jarg1, String jarg2);
  public final static native void qtSetBindingsVersion(long jarg1, int jarg2, int jarg3);
  public final static native long qtCreateClass(long jarg1, String jarg2);
  public final static native void qtFinalizeClass(long jarg1, long jarg2);
  public final static native void qtCreateProperty(long jarg1, long jarg2, String jarg3, String jarg4);
  public final static native void qtSetClassCompanionType(long jarg1, long jarg2, int jarg3);
  public final static native long qtCreateObject(long jarg1, long jarg2);
  public final static native void qtDestroyObject(long jarg1, long jarg2);
  public final static native void qtWriteProperty(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long qtReadProperty(long jarg1, long jarg2, String jarg3);
  public final static native void qtPropertyChanged(long jarg1, long jarg2, String jarg3);
  public final static native int qtMain(int jarg1, String[] jarg2, String jarg3);
  public final static native int qtMainSimple(String jarg1);
  public final static native int qtValueType(long jarg1);
  public final static native String qtValueTypeName(int jarg1);
  public final static native long qtValueCopy(long jarg1);
  public final static native void qtValueFree(long jarg1);
  public final static native int qtValueToInt(long jarg1);
  public final static native long qtValueFromInt(int jarg1);
}
