# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -r -outdir swig/ qmlbindings.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = RSWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  assign(defName,  .values,  envir = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################


setClass('_p_QtQmlBindings_t', contains = 'ExternalReference')
setClass('_p_QtClass_t', contains = 'ExternalReference')
setClass('_p_QtValue_t', contains = 'ExternalReference')
setClass('_p_QtValuePointer_t', contains = 'ExternalReference')
setClass('_p_f_p_q_const__char__p_void',
        prototype = list(parameterTypes = c('_p_char'),
                        returnType = '_p_f_p_q_const__char__p_void'),
        contains = 'CRoutinePointer')

##
setClass('_p_f_p_void__void',
        prototype = list(parameterTypes = c('_p_void'),
                        returnType = '_p_f_p_void__void'),
        contains = 'CRoutinePointer')

##
setClass('_p_f_p_void_p_q_const__char__p_QtValue_t',
        prototype = list(parameterTypes = c('_p_void', '_p_char'),
                        returnType = '_p_f_p_void_p_q_const__char__p_QtValue_t'),
        contains = 'CRoutinePointer')

##
setClass('_p_f_p_void_p_q_const__char_p_struct_QtValue_t__void',
        prototype = list(parameterTypes = c('_p_void', '_p_char', '_p_QtValue_t'),
                        returnType = '_p_f_p_void_p_q_const__char_p_struct_QtValue_t__void'),
        contains = 'CRoutinePointer')

##



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})

# Start of qtCreateQmlBindings

`qtCreateQmlBindings` = function(createObjectFn, destroyObjectFn, readPropertyFn, writePropertyFn)
{
  if (inherits(createObjectFn, "ExternalReference")) createObjectFn = slot(createObjectFn,"ref") 
  if (inherits(destroyObjectFn, "ExternalReference")) destroyObjectFn = slot(destroyObjectFn,"ref") 
  if (inherits(readPropertyFn, "ExternalReference")) readPropertyFn = slot(readPropertyFn,"ref") 
  if (inherits(writePropertyFn, "ExternalReference")) writePropertyFn = slot(writePropertyFn,"ref") 
  ;ans = .Call('R_swig_qtCreateQmlBindings', createObjectFn, destroyObjectFn, readPropertyFn, writePropertyFn, PACKAGE='qmlbindings');
  ans <- new("_p_QtQmlBindings_t", ref=ans) ;
  
  ans
  
}

attr(`qtCreateQmlBindings`, 'returnType') = '_p_QtQmlBindings_t'
attr(`qtCreateQmlBindings`, "inputTypes") = c('_p_f_p_q_const__char__p_void', '_p_f_p_void__void', '_p_f_p_void_p_q_const__char__p_QtValue_t', '_p_f_p_void_p_q_const__char_p_struct_QtValue_t__void')
class(`qtCreateQmlBindings`) = c("SWIGFunction", class('qtCreateQmlBindings'))

# Start of qtDestroyQmlBindings

`qtDestroyQmlBindings` = function(bindings)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  ;.Call('R_swig_qtDestroyQmlBindings', bindings, PACKAGE='qmlbindings');
  
}

attr(`qtDestroyQmlBindings`, 'returnType') = 'void'
attr(`qtDestroyQmlBindings`, "inputTypes") = c('_p_QtQmlBindings_t')
class(`qtDestroyQmlBindings`) = c("SWIGFunction", class('qtDestroyQmlBindings'))

# Start of qtSetBindingsObjectIdentityType

`qtSetBindingsObjectIdentityType` = function(bindings, typeName)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  typeName = as(typeName, "character"); 
  ;.Call('R_swig_qtSetBindingsObjectIdentityType', bindings, typeName, PACKAGE='qmlbindings');
  
}

attr(`qtSetBindingsObjectIdentityType`, 'returnType') = 'void'
attr(`qtSetBindingsObjectIdentityType`, "inputTypes") = c('_p_QtQmlBindings_t', 'character')
class(`qtSetBindingsObjectIdentityType`) = c("SWIGFunction", class('qtSetBindingsObjectIdentityType'))

# Start of qtSetBindingsUri

`qtSetBindingsUri` = function(bindings, uri)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  uri = as(uri, "character"); 
  ;.Call('R_swig_qtSetBindingsUri', bindings, uri, PACKAGE='qmlbindings');
  
}

attr(`qtSetBindingsUri`, 'returnType') = 'void'
attr(`qtSetBindingsUri`, "inputTypes") = c('_p_QtQmlBindings_t', 'character')
class(`qtSetBindingsUri`) = c("SWIGFunction", class('qtSetBindingsUri'))

# Start of qtSetBindingsVersion

`qtSetBindingsVersion` = function(bindings, majorVersion, minorVersion)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  majorVersion = as.integer(majorVersion);
  
  if(length(majorVersion) > 1) {
    warning("using only the first element of majorVersion");
  };
  
  minorVersion = as.integer(minorVersion);
  
  if(length(minorVersion) > 1) {
    warning("using only the first element of minorVersion");
  };
  
  ;.Call('R_swig_qtSetBindingsVersion', bindings, majorVersion, minorVersion, PACKAGE='qmlbindings');
  
}

attr(`qtSetBindingsVersion`, 'returnType') = 'void'
attr(`qtSetBindingsVersion`, "inputTypes") = c('_p_QtQmlBindings_t', 'integer', 'integer')
class(`qtSetBindingsVersion`) = c("SWIGFunction", class('qtSetBindingsVersion'))

# Start of qtCreateClass

`qtCreateClass` = function(bindings, className)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  className = as(className, "character"); 
  ;ans = .Call('R_swig_qtCreateClass', bindings, className, PACKAGE='qmlbindings');
  ans <- new("_p_QtClass_t", ref=ans) ;
  
  ans
  
}

attr(`qtCreateClass`, 'returnType') = '_p_QtClass_t'
attr(`qtCreateClass`, "inputTypes") = c('_p_QtQmlBindings_t', 'character')
class(`qtCreateClass`) = c("SWIGFunction", class('qtCreateClass'))

# Start of qtFinalizeClass

`qtFinalizeClass` = function(bindings, klass)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(klass, "ExternalReference")) klass = slot(klass,"ref") 
  ;.Call('R_swig_qtFinalizeClass', bindings, klass, PACKAGE='qmlbindings');
  
}

attr(`qtFinalizeClass`, 'returnType') = 'void'
attr(`qtFinalizeClass`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_QtClass_t')
class(`qtFinalizeClass`) = c("SWIGFunction", class('qtFinalizeClass'))

# Start of qtCreateProperty

`qtCreateProperty` = function(bindings, klass, propertyType, propertyName)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(klass, "ExternalReference")) klass = slot(klass,"ref") 
  propertyType = as(propertyType, "character"); 
  propertyName = as(propertyName, "character"); 
  ;.Call('R_swig_qtCreateProperty', bindings, klass, propertyType, propertyName, PACKAGE='qmlbindings');
  
}

attr(`qtCreateProperty`, 'returnType') = 'void'
attr(`qtCreateProperty`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_QtClass_t', 'character', 'character')
class(`qtCreateProperty`) = c("SWIGFunction", class('qtCreateProperty'))

defineEnumeration('_QtClassCompanionType',
                    .values = c(
                        'QtQObjectCompanion' = 0, 
                        'QuickPaintedItemCompanion' = 1, 
                        'QtForeginWindowCompanion' = 2
))
# Start of qtSetClassCompanionType

`qtSetClassCompanionType` = function(bindings, klass, companionType)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(klass, "ExternalReference")) klass = slot(klass,"ref") 
  companionType = enumToInteger(companionType, "_QtClassCompanionType"); 
  
  if(length(companionType) > 1) {
    warning("using only the first element of companionType");
  };
  
  ;.Call('R_swig_qtSetClassCompanionType', bindings, klass, companionType, PACKAGE='qmlbindings');
  
}

attr(`qtSetClassCompanionType`, 'returnType') = 'void'
attr(`qtSetClassCompanionType`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_QtClass_t', 'character')
class(`qtSetClassCompanionType`) = c("SWIGFunction", class('qtSetClassCompanionType'))

# Start of qtCreateObject

`qtCreateObject` = function(bindings, klass)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(klass, "ExternalReference")) klass = slot(klass,"ref") 
  ;ans = .Call('R_swig_qtCreateObject', bindings, klass, PACKAGE='qmlbindings');
  ans <- new("_p_void", ref=ans) ;
  
  ans
  
}

attr(`qtCreateObject`, 'returnType') = '_p_void'
attr(`qtCreateObject`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_QtClass_t')
class(`qtCreateObject`) = c("SWIGFunction", class('qtCreateObject'))

# Start of qtDestroyObject

`qtDestroyObject` = function(bindings, object)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(object, "ExternalReference")) object = slot(object,"ref") 
  ;.Call('R_swig_qtDestroyObject', bindings, object, PACKAGE='qmlbindings');
  
}

attr(`qtDestroyObject`, 'returnType') = 'void'
attr(`qtDestroyObject`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_void')
class(`qtDestroyObject`) = c("SWIGFunction", class('qtDestroyObject'))

# Start of qtWriteProperty

`qtWriteProperty` = function(bindings, object, propertyName, value)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(object, "ExternalReference")) object = slot(object,"ref") 
  propertyName = as(propertyName, "character"); 
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;.Call('R_swig_qtWriteProperty', bindings, object, propertyName, value, PACKAGE='qmlbindings');
  
}

attr(`qtWriteProperty`, 'returnType') = 'void'
attr(`qtWriteProperty`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_void', 'character', '_p_QtValue_t')
class(`qtWriteProperty`) = c("SWIGFunction", class('qtWriteProperty'))

# Start of qtReadProperty

`qtReadProperty` = function(bindings, object, propertyName)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(object, "ExternalReference")) object = slot(object,"ref") 
  propertyName = as(propertyName, "character"); 
  ;ans = .Call('R_swig_qtReadProperty', bindings, object, propertyName, PACKAGE='qmlbindings');
  ans <- new("_p_QtValue_t", ref=ans) ;
  
  ans
  
}

attr(`qtReadProperty`, 'returnType') = '_p_QtValue_t'
attr(`qtReadProperty`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_void', 'character')
class(`qtReadProperty`) = c("SWIGFunction", class('qtReadProperty'))

# Start of qtPropertyChanged

`qtPropertyChanged` = function(bindings, object, propertyName)
{
  if (inherits(bindings, "ExternalReference")) bindings = slot(bindings,"ref") 
  if (inherits(object, "ExternalReference")) object = slot(object,"ref") 
  propertyName = as(propertyName, "character"); 
  ;.Call('R_swig_qtPropertyChanged', bindings, object, propertyName, PACKAGE='qmlbindings');
  
}

attr(`qtPropertyChanged`, 'returnType') = 'void'
attr(`qtPropertyChanged`, "inputTypes") = c('_p_QtQmlBindings_t', '_p_void', 'character')
class(`qtPropertyChanged`) = c("SWIGFunction", class('qtPropertyChanged'))

# Start of qtMain

`qtMain` = function(s_argc, s_argv, mainQmlFilePath, .copy = FALSE)
{
  s_argc = as.integer(s_argc);
  
  if(length(s_argc) > 1) {
    warning("using only the first element of s_argc");
  };
  
  if (inherits(s_argv, "ExternalReference")) s_argv = slot(s_argv,"ref") 
  mainQmlFilePath = as(mainQmlFilePath, "character"); 
  ;.Call('R_swig_qtMain', s_argc, s_argv, mainQmlFilePath, as.logical(.copy), PACKAGE='qmlbindings');
  
}

attr(`qtMain`, 'returnType') = 'integer'
attr(`qtMain`, "inputTypes") = c('integer', 'character', 'character')
class(`qtMain`) = c("SWIGFunction", class('qtMain'))

# Start of qtMainSimple

`qtMainSimple` = function(mainQmlFilePath, .copy = FALSE)
{
  mainQmlFilePath = as(mainQmlFilePath, "character"); 
  ;.Call('R_swig_qtMainSimple', mainQmlFilePath, as.logical(.copy), PACKAGE='qmlbindings');
  
}

attr(`qtMainSimple`, 'returnType') = 'integer'
attr(`qtMainSimple`, "inputTypes") = c('character')
class(`qtMainSimple`) = c("SWIGFunction", class('qtMainSimple'))

# Start of qtValueType

`qtValueType` = function(value, .copy = FALSE)
{
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;.Call('R_swig_qtValueType', value, as.logical(.copy), PACKAGE='qmlbindings');
  
}

attr(`qtValueType`, 'returnType') = 'integer'
attr(`qtValueType`, "inputTypes") = c('_p_QtValue_t')
class(`qtValueType`) = c("SWIGFunction", class('qtValueType'))

# Start of qtValueTypeName

`qtValueTypeName` = function(s_arg1)
{
  s_arg1 = as.integer(s_arg1);
  
  if(length(s_arg1) > 1) {
    warning("using only the first element of s_arg1");
  };
  
  ;.Call('R_swig_qtValueTypeName', s_arg1, PACKAGE='qmlbindings');
  
}

attr(`qtValueTypeName`, 'returnType') = 'character'
attr(`qtValueTypeName`, "inputTypes") = c('integer')
class(`qtValueTypeName`) = c("SWIGFunction", class('qtValueTypeName'))

# Start of qtValueCopy

`qtValueCopy` = function(value)
{
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;ans = .Call('R_swig_qtValueCopy', value, PACKAGE='qmlbindings');
  ans <- new("_p_QtValue_t", ref=ans) ;
  
  ans
  
}

attr(`qtValueCopy`, 'returnType') = '_p_QtValue_t'
attr(`qtValueCopy`, "inputTypes") = c('_p_QtValue_t')
class(`qtValueCopy`) = c("SWIGFunction", class('qtValueCopy'))

# Start of qtValueFree

`qtValueFree` = function(value)
{
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;.Call('R_swig_qtValueFree', value, PACKAGE='qmlbindings');
  
}

attr(`qtValueFree`, 'returnType') = 'void'
attr(`qtValueFree`, "inputTypes") = c('_p_QtValue_t')
class(`qtValueFree`) = c("SWIGFunction", class('qtValueFree'))

# Start of qtValueToInt

`qtValueToInt` = function(value, .copy = FALSE)
{
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;.Call('R_swig_qtValueToInt', value, as.logical(.copy), PACKAGE='qmlbindings');
  
}

attr(`qtValueToInt`, 'returnType') = 'integer'
attr(`qtValueToInt`, "inputTypes") = c('_p_QtValue_t')
class(`qtValueToInt`) = c("SWIGFunction", class('qtValueToInt'))

# Start of qtValueFromInt

`qtValueFromInt` = function(value)
{
  value = as.integer(value);
  
  if(length(value) > 1) {
    warning("using only the first element of value");
  };
  
  ;ans = .Call('R_swig_qtValueFromInt', value, PACKAGE='qmlbindings');
  ans <- new("_p_QtValue_t", ref=ans) ;
  
  ans
  
}

attr(`qtValueFromInt`, 'returnType') = '_p_QtValue_t'
attr(`qtValueFromInt`, "inputTypes") = c('integer')
class(`qtValueFromInt`) = c("SWIGFunction", class('qtValueFromInt'))


