/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class QtClassCompanionType {
  public final static QtClassCompanionType QtQObjectCompanion = new QtClassCompanionType("QtQObjectCompanion");
  public final static QtClassCompanionType QuickPaintedItemCompanion = new QtClassCompanionType("QuickPaintedItemCompanion");
  public final static QtClassCompanionType QtForeginWindowCompanion = new QtClassCompanionType("QtForeginWindowCompanion");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static QtClassCompanionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + QtClassCompanionType.class + " with value " + swigValue);
  }

  private QtClassCompanionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private QtClassCompanionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private QtClassCompanionType(String swigName, QtClassCompanionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static QtClassCompanionType[] swigValues = { QtQObjectCompanion, QuickPaintedItemCompanion, QtForeginWindowCompanion };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

